apiVersion: apps/v1
kind: Deployment
metadata:
  name: "panv2-service"
spec:
  selector:
    matchLabels:
      app_name: "panv2-service"
  template:
    metadata:
      annotations:
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagsource: "flaghouse/panv2-service-flagsource"
      labels:
        app_name: "panv2-service"
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: docker-hub-token1
      - name: docker-hub-token2
      - name: dockerhubsignzy
      - name: dockerhubsignzy2
      - name: docker-hub-token7
      - name: docker-hub-token8
      - name: docker-hub-token9
      hostAliases: []
      containers:
      - name: "panv2-service"
        image: signzy/panv2-service
        imagePullPolicy: Always
        ports:
        - containerPort: 52216
          protocol: TCP