apiVersion: v1
kind: Service
metadata:
  name: "panv2-service-new"
  namespace: apis
spec:
  type: NodePort
  selector:
    env: staging
    app_name: "panv2-service-new"
  ports:
  - name: http-panv2-service-new
    port: 52216
    protocol: TCP
    nodePort: 32218
