apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "panv2-service"
  namespace: apis
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: panv2-service
